name: ttrpgcharacter
description: "TTRPG Character Manager"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  go_router: ^17.0.1
  hive_ce: ^2.19.2
  hive_ce_flutter: ^2.3.4
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
